### ISSUE TITLE
Expand Formatter support

### ISSUE THREAD

**Issue by dflemstr** [serde-rs/json#142]
I want to offer pretty printing of JSON objects beyond what the `PrettyFormatter` can supply, for example color support or intelligent line wrapping.  For that, I'd like to expose more callbacks to control formatting.

Ideally I would like to be able to color every "token type" differently.

Currently, these things can be colored:

  * `{` `}` `[` `]` `,` `:` trivially in `fn open(...)`, `fn colon(...)`, `fn comma(...)` and `fn close(...)`
  * Field names (by checking if `ch == "{"` in `fn open(...)` and `fn comma(...)` and writing color info accordingly)
  * Field values and array elements (by writing color info in `fn open(...)`, `fn comma(...)` and `fn close(...)`)

Note that values in general cannot be colored because when serializing an `i32` for example, no formatting callbacks are called.  The current situation also leads to awkward code like this: https://github.com/dflemstr/rq/blob/bb845ea5318db377927cf10e75eff6d44194129c/src/value/json.rs#L142-L145

What would be nice is to have a callback for each JSON terminal.  This would involve:

  - [ ] Rename `fn open(...)` to `fn open_object/array(...)` (and `fn close(...)` to `fn close_object/array(...)`), but there can be a default method body for backwards compatibility.
  - [ ] Add callbacks for all missing JSON terminals:
    - [ ] `fn object_key(...)`
    - [ ] `fn string(...)`
    - [ ] `fn number(...)`
    - [ ] `fn bool(..., bool)`
    - [ ] `fn null(...)`
  - [ ] Maybe add support for low-level terminals:
    - [ ] `fn open/close_string(...)`.
    - [ ] `fn string_char(..., char)`
    - [ ] `fn string_escape(..., Escape)` where `enum Escape { Quote, ..., Unicode([u8; 4]) }` or something.
    - [ ] `fn number_digit(..., char)` etc.

This probably means that the `Serializer` would never write to its `Write` on its own, but delegate everything to the `Formatter`.

I could implement this change if people think it's a good idea.  I'm mostly seeking feedback on the approach first.

**Comment by dtolnay** [comment]
I think this is a good idea as long as it does not affect performance when using CompactFormatter because people tend to care about that. Of the functions you suggested, I think we can make all of those work efficiently except `fn string(...)` because it would require heap-allocating the entire escaped string even in cases where serde_json currently [optimizes it away](https://github.com/serde-rs/json/blob/146cf17f78c0a86801b10f0250e86d1078d5f450/json/src/ser.rs#L853-L857). I would prefer to stick to lower-level calls.

I would suggest looking at all the writer calls made in the current serializer and turning those into Formatter methods. For example [this call](https://github.com/serde-rs/json/blob/146cf17f78c0a86801b10f0250e86d1078d5f450/json/src/ser.rs#L860) would become something like `fn string_fragment(&[u8])`.

A PR would be welcome.

**Comment by dtolnay** [comment]
Also feel free to not worry about backward compatibility. Based on GitHub search you are the only one using this API. It is a breaking change so it will need to go in 0.9.0, but you can change the Formatter trait in whatever way makes the most sense.
