### ISSUE TITLE
How to use the "to_value" inside the implementation of Serialize for my type?

### ISSUE THREAD

**Issue by vessd** [serde-rs/json#223]
I want to get a multi-level object from my type.
```rust
use serde::ser::{Serializer, Serialize, SerializeMap};
use serde_json::{self, Map};

enum Action {
    Start(Ids),
    Stop(Ids),
    ...
}

impl Serialize for Action {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where S: Serializer
    {
        let mut arguments = Map::new();
        match *self {
            Action::Start(ref id) => {
                arguments.insert("ids".to_string(), serde_json::to_value(t)?); //error
                let mut map = serializer.serialize_map(Some(2))?;
                map.serialize_key("arguments")?;
                map.serialize_value(&arguments)?;
                map.serialize_key("method")?;
                map.serialize_value("start")?;
                map.end()
            }
            Action::Stop(ref id) => {
                ...
            }
            ...
        }
    }
}
```
I got the error for this line:
`arguments.insert("ids".to_string(), serde_json::to_value(t)?);`

> the trait `std::convert::From<serde_json::Error>` is not implemented for `<S as serde::Serializer>::Error`

How can I convert `serde_json::Error` in `<S as serde::Serializer>::Error`?

**Comment by dtolnay** [comment]
The `to_value` returns an error of type `serde_json::Error` and the serializer `S` may have a totally different error type. Whatever error type it has, we require that it is constructible from a Display: [`serde::ser::Error::custom`](https://docs.serde.rs/serde/ser/trait.Error.html#tymethod.custom). You can use it like this:

```rust
serde_json::to_value(t).map_err(ser::Error::custom)?
```

**Comment by vessd** [comment]
Thank you.
But I do not understand one thing.
When I call the function serialize_value, I refer to [this function](https://github.com/serde-rs/json/blob/28a38db66c80e7eb96487954fd3b233f3670d8c9/json/src/value.rs#L1061), right? Then, this function calls the function [`try!(to_value())`](https://github.com/serde-rs/json/blob/28a38db66c80e7eb96487954fd3b233f3670d8c9/json/src/value.rs#L1068) and as a result returns the `S::Error`.
What is the difference?

**Comment by dtolnay** [comment]
Written out using fully qualified paths, here are the three relevant function signatures:

```rust
// signature of `serde_json::ser::SerializeMap::serialize_value`
fn serialize_value<T>(&mut self, value: &T) -> Result<(), serde_json::Error>
    where T: ?Sized + serde::Serialize

// signature of `serde_json::to_value`
fn to_value<T>(value: T) -> Result<serde_json::Value, serde_json::Error>
    where T: serde::Serialize

// signature of `vessd::Action::serialize`
fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where S: serde::Serializer
```

So `serialize_value` is allowed to call `to_value` without doing an error conversion because both functions have exactly the same error type.

Your function has a different error type. For example if `S` happens to be `bincode::Serializer`, the error type is totally different from `to_value`'s error type.

**Comment by vessd** [comment]
And how can I call the function `serialize_value` in my serialize implementation, if they return different types?

> `fn serialize_value<T>(&mut self, value: &T) -> Result<(), serde_json::Error>`

> `fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>`

**Comment by dtolnay** [comment]
Well those two actually have the same error type!

Here is the relevant part of the [`Serializer`](https://docs.serde.rs/serde/ser/trait.Serializer.html) trait:

```rust
trait Serializer {
    type Ok;
    type Error: Error;
    type SerializeMap: SerializeMap<Ok=Self::Ok, Error=Self::Error>;
    fn serialize_map(self, len: Option<usize>) -> Result<Self::SerializeMap, Self::Error>;
    /* ... */
}
```

Here is the relevant part of the [`SerializeMap`](https://docs.serde.rs/serde/ser/trait.SerializeMap.html) trait:

```rust
trait SerializeMap {
    type Ok;
    type Error: Error;
    fn serialize_value<T>(&mut self, value: &T) -> Result<(), Self::Error>;
        where T: ?Sized + serde::Serialize;
    /* ... */
}
```

So that means if you have a `Serializer` of type `S` and call `S::serialize_map` then the error type is `S::Error`, but if it succeeds and gives you a `SerializeMap` instance and you call `SerializeMap::serialize_value` on it, the error type is still `S::Error`.

Any `SerializeMap` (or other associated type) that you get from a `Serializer` is required to have the same error type as the `Serializer`, and that is the error type that your `serialize` function is supposed to return.

**Comment by vessd** [comment]
Unfortunately I don't get it.

> Well those two actually have the same error type!

Does this mean that that `to_value()` inside `serialize_value()` returns `S::Error` too?
Because `serialize_value()` call `try!(to_value(&value))` and I call `serialize_value(&arguments)?` inside `fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>`. So `to_value()` should return `S::Error` somehow...

**Comment by dtolnay** [comment]
Forget about the fact that you are using this Action type with JSON. The signature of the Serialize trait is such that it is required to work with any serializer.

```rust
pub trait Serialize {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where S: Serializer;
}
```

The type parameter `S` means that the caller decides what format they want to use, and the implementation needs to handle any format.

So imagine that a caller decides they want to use Action's Serialize implementation with [Bincode](https://github.com/TyOverby/bincode)'s Serializer. That means for that call, `S = bincode::Serializer` and `S::Error = bincode::Error`.

If your Serialize implementation for Action calls `serde_json::to_value`, it gets back a `serde_json::Error`. It can convert that error to `S::Error` (whatever it may be, in this case `bincode::Error`) by using `serde::ser::Error::custom`.

And if your Serialize implementation for Action calls `serializer.serialize_map()` or `map.serialize_value()` then the Serializer is responsible for guaranteeing that those return the correct error type. In this case it will call `bincode::Serializer::serialize_map` which returns `bincode::Error` and `bincode::SerializeMap::serialize_value` which returns `bincode::Error` so everything is okay.

Now somebody else decides to use Actions' Serialize implementation with a JSON serializer. So now `S = serde_json::Serializer` and `S::Error = serde_json::Error`.

If your Serialize implementation for Action calls `serializer.serialize_map()` then that is really `serde_json::Serializer::serialize_map` and `map.serialize_value()` is really `serde_json::SerializeMap::serialize_value`, both of which return `serde_json::Error`. And `serde_json::SerializeMap::serialize_value` can call `serde_json::to_value` because `to_value` always returns `serde_json::Error`.

**Comment by vessd** [comment]
Thank you so much.
I missed the fact that I realize the `fn serialize<S>` for any `Serializer`, and not just for `serde_json::Serializer`.
And now my code looks bad. I should rework this place.

**Comment by dtolnay** [comment]
The [`json!` macro](https://docs.serde.rs/serde_json/macro.json.html) may be helpful in cleaning this up, depending on what the rest of the code is doing. Something like:

```rust
impl Serialize for Action {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where S: Serializer
    {
        let value = match *self {
            Action::Start(ref ids) => {
                json!({
                    "arguments": {
                        "ids": ids
                    },
                    "method": "start"
                })
            }
            Action::Stop(ref ids) => {
                /* ... */
            }
            /* ... */
        };
        value.serialize(serializer)
    }
}
```

**Comment by vessd** [comment]
I think it would be better if I use this macro in the "main" function. I mean that a generalized function should not be affected by serde_json.
