### ISSUE TITLE
where did StreamDeserializer::new go?

### ISSUE THREAD

**Issue by softprops** [serde-rs/json#234]
Im upgrading from 0.8 to 0.9 and noticed there was an undocumented breaking change for StreamDeserializer. I can no longer construct an instance for one a type implements Deserialize. it looks like its now behind into_iter on Deserialize for types that implement Read. Please advise

**Comment by dtolnay** [comment]
You can stream any JSON deserializer now:

https://docs.serde.rs/serde_json/de/struct.Deserializer.html#method.into_iter

Previously the only way to make a stream deserializer was StreamDeserializer::new which took an iterator of io::Result\<u8>. This made it impossible to apply any of the optimizations that we use for &[u8] and &str input in the non-streaming case. Rather than mirroring all of the Deserializer constructors (from_reader, from_slice, from_str, from_iter) in StreamDeserializer, we let you take any Deserializer and upgrade it to a StreamDeserializer.

Let me keep this issue open until i add examples to the StreamDeserializer rustdoc and into_iter method.

#### Before:

```diff
  let data = "{ ... }";
- let mut stream: StreamDeserializer<Value, _> = StreamDeserializer::new(
-     data.as_bytes().iter().map(|byte| Ok(*byte))
- );
```

#### After:

```diff
  let data = "{ ... }";
+ let mut stream = Deserializer::from_str(data).into_iter::<Value>();
```

**Comment by softprops** [comment]
My use case is a stream of data  https://github.com/softprops/lux/blob/master/src/pod.rs#L17. I relied on the ability to produce a stream of deserialization where the source may not be in memory, in this case hypers support for chunked http. Is this still supported in serde json?

**Comment by oli-obk** [comment]
@softprops: There's [`from_reader`](https://docs.serde.rs/serde_json/de/fn.from_reader.html). Is that what you need?

**Comment by softprops** [comment]
I'll take a look again tonight

**Comment by dtolnay** [comment]
You want:

```rust
let s = serde_json::Deserializer::from_iter(bytes).into_iter::<PodEvent>();
```

**Comment by softprops** [comment]
> let s = serde_json::Deserializer::from_iter(bytes).into_iter::<PodEvent>();

thanks @dtolnay  that works great!

**Comment by dtolnay** [comment]
Reopening until I get a chance to add an example to the StreamDeserializer documentation.

**Comment by softprops** [comment]
Cool. It's been an awesome help to me. I made a crate that did a similar thing way back when there was only rust serialize - https://github.com/softprops/jed once I discovered this in serde, I never turned back!

**Comment by sorccu** [comment]
How might one place the new `StreamDeserializer` into a struct, where the full type needs to be known, yet Read and friends are private? Trying to update some late 2016 code that looks pretty much like this:

```rust
pub struct Client {
    reader: StreamDeserializer<serde_json::Value, Bytes<TcpStream>>,
}
```

**Comment by dtolnay** [comment]
```rust
pub struct Client<D> {
    reader: D,
}

fn f<D>(c: Client<D>)
    where D: Iterator<Item = Result<serde_json::Value, serde_json::Error>>
```

It's not great. I opened #250 to add a nicer way.

```rust
pub struct Client<R> {
    reader: StreamDeserializer<R, serde_json::Value>,
}

fn f<R>(c: Client<R>)
    where R: serde_json::de::Read
```

**Comment by sorccu** [comment]
Ok, forgive me for being a bit rusty (or not rusty enough I suppose) but unfortunately it's been a while since I last had a chance to play with Rust, how would I actually assign something to that? Here's a bit more fleshed out snippet:

```rust
use std::io::{Read, Bytes};
use std::net::{TcpStream, ToSocketAddrs};

use serde_json::{self, Deserializer};

pub struct Client<D> where D: Iterator<Item = serde_json::Result<serde_json::Value>> {
    writer: TcpStream,
    reader: D,
}

impl<D> Client<D> where D: Iterator<Item = serde_json::Result<serde_json::Value>> {
    pub fn open<A: ToSocketAddrs>(addr: A) -> Result<Client<D>> {
        let writer = try!(TcpStream::connect(addr).map_err(Error::Connect));
        let reader = try!(writer.try_clone().map_err(Error::Io));
        Ok(Client {
            writer: writer,
            reader: Deserializer::from_iter(reader.bytes()).into_iter::<serde_json::Value>()
        })
    }
}
```

That errors with:

```
24 |           Ok(Client {
   |  ____________^ starting here...
26 | |             writer: writer,
27 | |             reader: Deserializer::from_iter(reader.bytes()).into_iter()
28 | |         })
   | |_________^ ...ending here: expected type parameter, found struct `serde_json::StreamDeserializer`
   |
   = note: expected type `rpc::client::Client<D>`
              found type `rpc::client::Client<serde_json::StreamDeserializer<serde_json::read::IteratorRead<std::io::Bytes<std::net::TcpStream>>, serde_json::Value>>`
```

**Comment by dtolnay** [comment]
The problem is that the function signature of `open` says that the caller is allowed to decide what D is, but in fact the body of `open` wants to be able to decide what D is. This is the problem that [impl Trait](https://github.com/rust-lang/rfcs/blob/master/text/1522-conservative-impl-trait.md) is designed to solve.

```rust
#![feature(conservative_impl_trait)]

pub fn open<A: ToSocketAddrs>(addr: A) -> Result<Client<impl Iterator<Item = serde_json::Result<serde_json::Value>>>>
```

In your case a simpler stable approach might be:

```rust
pub struct Client {
    writer: TcpStream,
    reader: Box<Iterator<Item = serde_json::Result<serde_json::Value>>>,
}

impl Client {
    pub fn open<A: ToSocketAddrs>(addr: A) -> Result<Client> {
        let writer = try!(TcpStream::connect(addr).map_err(Error::Connect));
        let reader = try!(writer.try_clone().map_err(Error::Io));
        Ok(Client {
            writer: writer,
            reader: Box::new(Deserializer::from_iter(reader.bytes()).into_iter()),
        })
    }
}
```

To explain the increase in complexity here - previous versions of serde_json had one StreamDeserializer type that treated all input sources the same, so it can be parameterized with an input iterator like Bytes\<TcpStream\> and an output type like serde_json::Value in a simple way. The downside is that it treats all input sources the same... so input that is &str or &[u8] would follow the same slow codepath as Iterator\<Item=io::Result\<u8\>\>. In the new serde_json we have a less nice workaround that allows us to optimize for &str and &[u8] input and once [specialization](https://github.com/rust-lang/rfcs/blob/master/text/1210-impl-specialization.md) is available, we can go back to nice bounds like Bytes\<TcpStream\>.

**Comment by sorccu** [comment]
I did actually already try impl trait, however in the end it asked me to
specify the return value anyway on the calling side. I'll try to take
another look later, possible there was some sort of a mistake.

Thanks for the helpful responses :)
