### ISSUE TITLE
Expose whether error is caused by EOF

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/json#245]
In streaming use cases you want to treat `{"x": true,` differently from `{]`. One of them you retry later once you have more data, the other is just an error.

cc @vorner

**Comment by dtolnay** [comment]
Let's add:

- is_eof()
- is_syntax()
- is_io()

where I think eof errors are not syntax errors.

**Comment by vorner** [comment]
Just to clarify, if I have a struct, let's say:

```rust
#[derive(deserialize)]
struct Point {
  x: u64,
  y: u64,
};
```

And pass this JSON:

```json
{"a": 16}
```

What kind of error is this? It's not exactly syntax error, it just doesn't fit into the form. Maybe having another one for these kinds of errors would be nice?

**Comment by Kixunil** [comment]
I'd prefer making IO error associated type, so that if you parse from `&str`, it's statically known that IO error can't occur. Similarly, in case of serialising, no error can happen at all.

**Comment by dtolnay** [comment]
> What kind of error is this? It's not exactly syntax error, it just doesn't fit into the form. Maybe having another one for these kinds of errors would be nice?

Let's call this a data error - the syntax was valid but the data was wrong somehow. err.is_data()?

**Comment by dtolnay** [comment]
> I'd prefer making IO error associated type, so that if you parse from `&str`, it's statically known that IO error can't occur.

@Kixunil can you explain more about your use case that requires you to differentiate between IO errors and other types of errors? What are you doing that is more than just printing the error as a string, and why is it beneficial to know that IO errors can't occur?

**Comment by vorner** [comment]
> Let's call this a data error - the syntax was valid but the data was wrong somehow. err.is_data()?

That sounds like a good name to me :-).

**Comment by Kixunil** [comment]
@dtolnay I believe that it's more expressive design. The reasons led me to create [`genio`](https://github.com/Kixunil/genio) crate. In case of serde, serialisation is more interesting to me regarding error type.

I wrote `serde_json::to_string(my_obj).unwrap(); // Serialising to string can't fail.` but I have no way to be 100% sure it can't fail. If someone accidentally writes a code in library that would return `Err` my program would panic.

> What are you doing that is more than just printing the error as a string

I'm translating error messages. In case of `io::Error` I check if it's system error for which I have translation function. If it's not, I pass error untranslated. In case of `serde_json::Error` I have to pass all errors untranslated (even those that could be otherwise. Also, `serde_json::Error` doesn't provide any useful information beside error message, so I can't create translation for it. (This is not a blocker, but it'd be nice feature to have and use later.)

P.S.: Would be awesome if `serde_json` supported `genio`.

**Comment by dtolnay** [comment]
@Kixunil serde_json::to_string fails in both of these cases. Does that affect your perspective at all?

These are the cases noted in the serde_json::to_string [documentation](https://docs.serde.rs/serde_json/fn.to_string.html).

```rust
extern crate serde;
extern crate serde_json;

use std::collections::BTreeMap as Map;

use serde::{Serialize, Serializer};

struct S(u8);

impl Serialize for S {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where S: Serializer
    {
        match self.0 {
            0 => Err(serde::ser::Error::custom("zero is my least favorite byte")),
            _ => serializer.serialize_u8(self.0),
        }
    }
}

fn main() {
    println!("{}", serde_json::to_string(&S(0)).unwrap_err());

    let mut map = Map::new();
    map.insert(vec!["K"], "V");
    println!("{}", serde_json::to_string(&map).unwrap_err());
}
```

**Comment by Kixunil** [comment]
Oh, shit, I didn't notice. Is there a way to require `S::Error` to be `void::Void`?
