### ISSUE TITLE
More descriptive Error::description()

### ISSUE THREAD

**Issue by vorner** [serde-rs/json#246]
While formatting the deserialization error produces a descriptive output, the `description()` method only returns `syntax error`. This code illustrates that:

```rust
extern crate serde_json;
use std::error::Error;

use serde_json::de::from_str;
use serde_json::Value;

fn main() {
    match from_str::<Value>("{]") {
        Ok(_) => unreachable!(),
        Err(ref e) => println!("{}|{}", e.description(), e),
    };
}
```

It produces:

```
syntax error|key must be a string at line 1 column 2
```

**Comment by quodlibetor** [comment]
Along these lines, until the 0.9.4 (specifically 9aef53b15) release I was relying on the `Error::Syntax` fields being public so that I could use them to create an error message that referred back into the original text (I am pretty sure this is buggy near the edges of the source text):

```rust
pub fn humane_error(err: serde_json::Error, source: &str, url: &str) -> Error {
    match err {
        _ if source.len() == 0 => {
            ErrorKind::JsonError(format!("Tried to decode zero-length value: {}", err))
        },
        serde_json::Error::Syntax(message, start, end)
            => {
            ErrorKind::JsonError(
                format!("Error: {:?} between pipes: '{}|{}|{}'",
                        message,
                        &response[start..max(end - 1, 0)],
                        &response[max(end - 1, 0)..end],
                        &response[end..min(source.len(), end + 100)],
                )
            )
        }
        e => ErrorKind::JsonError(format!("Unexpected json error: {:?}", e))
    }.into()
}
```

This is primarily because I have a couple large structs that I'm debugging, and error messages like "Expect str not u64" (or similar) without the context are kind of rough.

There's a couple of things that I'd love, softly ordered by my understanding of how complex they'd be to implement:

1. Some programmatic way to get the position back out of a syntax error so that I can do what I've been doing for debugging.
2. Something like what I've got in `humane_error` there for the wild error cases. It looks like this would require a fully-buffered deserializer (or to only work on `&str` instead of `Read`?) which would be rough for particularly huge JSON values.
3. An error message that describes the field that serde errored on. (This looks like it would require an entirely different Deserializer? I don't think it would be implementable efficiently enough to be a reasonable thing to replace the current Deserializer with.) Bonus points if it's capable of giving the full [pointer](https://docs.serde.rs/serde_json/value/enum.Value.html#method.pointer) to the field being deserialized.

**Comment by dtolnay** [comment]
@quodlibetor other than the bug you called out, some other bugs in your humane_error function:

- The two numbers are line and column, not start and end :wink:
- If the error column is less than the line number, it panics
- If the column of the error is 0usize, subtracting 1 will wrap around to usize::MAX and then panic

In any case, I will be implementing your option 3. I already did it for serde_yaml in https://github.com/dtolnay/serde-yaml/pull/43 and the implementation was both easy and efficient so it will be on by default in serde_json.

**Comment by quodlibetor** [comment]
Ha, well I guess that's why you don't just use private struct fields as part of your app. Also read the names of the fields you're using.

And: hooray! Bonus points will be gratefully awarded.

**Comment by dtolnay** [comment]
@vorner I am happy to improve description() but can you give some more detail about why you would want to use description() rather than Display to print these errors? In general (across all error types and libraries) the messages you get from Display will be better than the ones from description() because of lifetime restrictions.

**Comment by vorner** [comment]
Basically, I wanted to store the error message for later. My first choice was to do:

```rust
let msg = e.description();
```

I did switch to:

```rust
let msg = format!("{}", e);
```

later on, but that feels unnatural. Or maybe I'm just too used to C++'s `e.what()`.

It's not anything important, it just looked like a forgotten first implementation than intention the current way, so I wanted to point it out. If this is how it is meant to be, then I'm 100% OK ignoring this.

**Comment by dtolnay** [comment]
I wouldn't say it is "meant to be" this way but I will say that even though the fix is a one-line trivial change, I am inclined to not fix it just to teach people not to use description(). As far as I know, description() is never ever what you want and it shouldn't have been part of the Error trait.

```rust
let msg = e.description();
```

The message you get is borrowed from the error, so if you store the message, you also have to store the error. That means there is no reason to store the message at all, because you could just borrow it from the error whenever you need.
