### ISSUE TITLE
Add PartialEq to Error

### ISSUE THREAD

**Issue by tredoe** [serde-rs/json#271]
Add #[derive(Debug, PartialEq)] to the error so it could be compared in tests of other libraries/apps that use your library.

Thanks in advance!

**Comment by tredoe** [comment]
https://github.com/serde-rs/json/pull/272

**Comment by dtolnay** [comment]
I would recommend comparing the errors as strings. Comparing the Error objects has a few hidden complexities:

- One of the variants contains `std::io::Error` which is not equality comparable.
- Can errors with the same message but different line and column be equal?
- If not, how do you construct errors with a particular line and column in your tests? Currently not something we expose.

If you are testing a Deserialize impl, that may be better solved by using serde_test rather than serde_json. See [linked-hash-map](https://github.com/contain-rs/linked-hash-map/blob/f757231e5cee84b57ca7908da23796e500394b37/tests/serde.rs) for an example, and some more [in our test suite](https://github.com/serde-rs/serde/blob/v0.9.10/test_suite/tests/test_de.rs#L893-L904).
