### ISSUE TITLE
`DeserializeSeed` support

### ISSUE THREAD

**Issue by cjhowe** [serde-rs/json#282]
Sometimes, it's necessary for a type to only implement `DeserializeSeed`, and not `Deserialize`. `serde_json` should support this use case, especially with the functions related to `from_trait`. I think the type should look something like this:

```
fn from_trait_seed<R, T>(seed: T, read: R) -> Result<T::Value>
    where R: Read,
          T: de::DeserializeSeed,
```

**Comment by dtolnay** [comment]
I would prefer not to address this by adding more public methods to serde_json. I think the DeserializeSeed use case is niche enough that we should instead design broadly applicable and composable APIs that satisfy this as well as lots of other use cases.

For deserializing a DeserializeSeed from JSON I think the composable API for it already exists. Here is some code using the example impl from the DeserializeSeed rustdoc. Do you think we need something like `from_trait_seed` in addition to this?

```rust
extern crate serde;
extern crate serde_json;

use std::fmt;
use serde::de::{Deserialize, DeserializeSeed, Deserializer, Visitor, SeqVisitor};

struct ExtendVec<'a, T: 'a>(&'a mut Vec<T>);

impl<'a, T> DeserializeSeed for ExtendVec<'a, T>
    where T: Deserialize
{
    type Value = ();

    fn deserialize<D>(self, deserializer: D) -> Result<Self::Value, D::Error>
        where D: Deserializer
    {
        struct ExtendVecVisitor<'a, T: 'a>(&'a mut Vec<T>);

        impl<'a, T> Visitor for ExtendVecVisitor<'a, T>
            where T: Deserialize
        {
            type Value = ();

            fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
                formatter.write_str("an array")
            }

            fn visit_seq<V>(self, mut visitor: V) -> Result<(), V::Error>
                where V: SeqVisitor
            {
                while let Some(elem) = visitor.visit()? {
                    self.0.push(elem);
                }
                Ok(())
            }
        }

        deserializer.deserialize_seq(ExtendVecVisitor(self.0))
    }
}

fn main() {
    let mut vec = vec![1, 2, 3];
    let mut deserializer = serde_json::Deserializer::from_str("[4, 5, 6]");
    ExtendVec(&mut vec).deserialize(&mut deserializer).unwrap();
    println!("{:?}", vec);
}
```

**Comment by cjhowe** [comment]
I think maybe at the scope of just this crate, that makes sense, but in the bigger `serde` ecosystem, I think it'd be good to maintain consistency as much as possible across different `Deserializer` crates. In this case, since that doesn't work for other `Deserializer` crates like `serde_yaml` which doesn't have the `Deserializer` exposed, it's worth it just to have a more consistent API across the two crates. Then again, I guess one could argue that's just a peculiarity when dealing with `serde_yaml`. I feel like all these helper functions should be generically implemented across `Deserializer` implementations anyways, perhaps with the help of an additional trait.

Specifically, since what I'm writing is a library, I don't want someone to use `serde_yaml` to do this one way, and not be able to apply that same kind of function when using `serde_json`. I think this makes sense because the different `serde` `Deserializer` crates are intended to be different "backends" to `serde`.

Anyways, this is mostly my opinion, so if you completely disagree, feel free to close this issue.

**Comment by dtolnay** [comment]
Thanks for the feedback. As you observed, I see that as a limitation of serde_yaml and https://github.com/dtolnay/serde-yaml/issues/44 is already tracking that issue.

The question of writing libraries that are generic across different byte-oriented serialization formats is tracked in https://github.com/serde-rs/serde/issues/644. The difficulty of applying that to the whole ecosystem is that not all formats are byte-oriented. You can have a Deserializer that deserializes from some data structure where you can't just feed it bytes to operate on. There is a path forward at the bottom of https://github.com/serde-rs/serde/issues/644#issuecomment-273038435 so I would love to get your feedback on that.

I am closing this issue because although I agree that there are things that need to be fixed, I think this need is more completely addressed by the two issues already tracked in https://github.com/dtolnay/serde-yaml/issues/44 and https://github.com/serde-rs/serde/issues/644.
