### ISSUE TITLE
Flattening newtype variant of an enum

### ISSUE THREAD

**Issue by anowell** [serde-rs/json#290]
I've hit a couple occasions where I wanted to serialize/deserialize an enum and basically flatten a particular newtype variant. This snippet from https://github.com/serde-rs/json/issues/181#issuecomment-269138635 pretty much captures what I'm after:

```
enum Field {
    Id,
    Event,
    Method,
    Other(String),  
}
```

I could imagine annotating just the `Other` variant with `serde(untagged)`, or I could imagine `#[serde(untagged)]` on the entire container still using using the variant name for unit variants. But the current behavior I see for `untagged` is that `"Event"` deserializes into `Field::Other("Event")` which isn't what I'm looking for, so I've been using custom serialization/deserialization to achieve this.

**Comment by dtolnay** [comment]
I agree, this case is common and could be handled a lot better by Serde. I am closing the issue because I would prefer to address this as part of the broader discussion around flattening in https://github.com/serde-rs/serde/issues/119. I see that this newtype variant case has already been brought up over there.

Here is one possible workaround to at least avoid handwritten impls:

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

#[derive(Serialize, Deserialize, Debug)]
#[serde(untagged)]
enum Anowell {
    Known(Field),
    Other(String),
}

#[derive(Serialize, Deserialize, Debug)]
enum Field {
    Id,
    Event,
    Method,
}

fn main() {
    println!("{:?}", serde_json::from_str::<Anowell>("\"Event\"").unwrap());
    println!("{:?}", serde_json::from_str::<Anowell>("\"Xyz\"").unwrap());

    println!("{}", serde_json::to_string(&Anowell::Known(Field::Event)).unwrap());
    println!("{}", serde_json::to_string(&Anowell::Other("Xyz".to_owned())).unwrap());
}
```
