### ISSUE TITLE
from_str fine; from_reader expected bound lifetime parameter but found concrete

### ISSUE THREAD

**Issue by OJFord** [serde-rs/json#331]
This works fine:

```rust
#[macro_use]
extern crate serde_derive;
extern crate serde_json;
use std::io::prelude::*;
use std::io::BufReader;
use std::fs::File;

#[derive(Debug, Deserialize)]
struct Foo<'a> {
    #[serde(borrow)]
    bar: &'a str,
}

fn main() {
    let deser: Foo = serde_json::from_str("{\"bar\": \"rab\"}").unwrap();
    println!("{:?}", deser);
}
```

but fails to compile if `main` is swapped for:

```rust
fn main() {
    let mut f = File::open("contents_as_above.json")?;
    let mut reader = BufReader::new(f);

    let deser: Foo = serde_json::from_reader(reader).unwrap();
    println!("{:?}", deser);
}
```

The error message is:
> error[E0279]: the requirement `for<'de> 'de : ` is not satisfied (`expected bound lifetime parameter 'de, found concrete lifetime`)
>  --> examples/one.rs:22:22
>   |
>22 |     let deser: Foo = serde_json::from_reader(reader).unwrap();
>   |                      ^^^^^^^^^^^^^^^^^^^^^^^
>   |
>   = note: required because of the requirements on the impl of `for<'de> _IMPL_DESERIALIZE_FOR_Foo::_serde::Deserialize<'de>` for `Foo<'_>`
>   = note: required because of the requirements on the impl of `_IMPL_DESERIALIZE_FOR_Foo::_serde::de::DeserializeOwned` for `Foo<'_>`
>   = note: required by `serde_json::from_reader`

where the red underlining (^^^) should be under `serde_json::from_reader`, stopping short of its argument.
 
Incidentally, E0279 is not yet in the error index, and I'm not sure I understand it fully (e.g. isn't `for<'de> 'de : ` syntactically incorrect; the second `'de` should be a type?) - so apologies if this is just due to my misuse.

**Comment by dtolnay** [comment]
Check out https://serde.rs/lifetimes.html where it explains what the two different possible Deserialize trait bounds mean. In serde_json, [`from_str`](https://docs.serde.rs/serde_json/fn.from_str.html) and [`from_reader`](https://docs.serde.rs/serde_json/fn.from_reader.html) require different bounds.

```rust
fn from_str<'a, T>(s: &'a str) -> Result<T>
    where T: Deserialize<'a>;

fn from_reader<R, T>(reader: R) -> Result<T>
    where R: Read,
          T: DeserializeOwned; // equivalent to T: for<'de> Deserialize<'de>
```

As explained on the site, the bound on `from_str` means that `T` can be deserialized from data of lifetime `'a`, while the bound on `from_reader` means that `T` can be deserialized from data of any (even arbitrarily short) lifetime. The reason is data from a reader is not kept in memory so there is nothing to borrow from.

Your options are to change `Foo` to be able to deserialize from any lifetime (by not borrowing) or to memory-map the input file using [`memmap`](https://crates.io/crates/memmap) and use [`from_slice`](https://docs.serde.rs/serde_json/fn.from_slice.html) to deserialize from the resulting in-memory slice of the file.

Remember to thank Rust for catching this bug! The borrow checker saved you from successfully deserializing a `Foo` containing garbage data.

**Comment by OJFord** [comment]
I understand now, thank you for your help!

> Remember to thank Rust for catching this bug! The borrow checker saved you from successfully deserializing a Foo containing garbage data.

:green_heart: Rust
