### ISSUE TITLE
Allow increasing recursion limit

### ISSUE THREAD

**Issue by Yoric** [serde-rs/json#334]
I am parsing/serializing pretty large JSON files and I regularly encounter `RecursionLimitExceeded`. I need a way to instantiate a `Serializer`/`Deserializer` with a much larger recursion limit.

Could we introduce code to let us tweak that?

**Comment by dtolnay** [comment]
Seems reasonable. What do you think the API should look like?

**Comment by dtolnay** [comment]
While we iterate on the API in #346, have you been able to figure out the appropriate recursion limit for your use case? If it is not too much more than the current default, we can raise the default without yet making it configurable.

**Comment by Yoric** [comment]
I believe that 1024 should be largely sufficient for my use cases.

**Comment by dtolnay** [comment]
Copied from the discussion in #346 -- the most important thing we still need to figure out here:

**How to reconcile with an eventual serde_json::Format.** I would feel more comfortable if we make more progress on https://github.com/serde-rs/serde/issues/644 before merging this. That issue will involve some data structure that describes JSON as a format, including whether to use indentation when serializing and presumably the recursion limit for deserializing. It may turn out to be a better API to treat that data structure as a builder for serde_json::Deserializer, rather than having builder methods directly on Deserializer.

**Comment by remexre** [comment]
Any progress/changes here? I've got a project (https://github.com/remexre/extlint) that's storing an OCaml AST in JSON; since in OCaml's AST, a list is transformed into a series of conses (i.e. `[1; 2; 3]` and `1 :: (2 :: (3 :: ([])))` have the same AST representation), which blows the recursion limit for a list literal of length 50.

I'm fine manually increasing the stack size, but being able to handle this is a high priority. Is the best solution still to apply #346 to the current master and add a note in my README that we use this custom version?

**Comment by Yoric** [comment]
This problem has caused me to switch to [json-rust](https://github.com/maciejhirsz/json-rust). Doesn't do nearly as many things as serde json, but it doesn't share this specific issue.

**Comment by remexre** [comment]
Yeah, I need serde for the project though, since I'm essentially transforming `JSON -> Rust datastructure -> Custom serialization` and I don't wanna write a custom Serialize for each AST node type.

**Comment by RReverser** [comment]
Would integrating https://github.com/alexcrichton/stacker help more reliably here perhaps? (by using `stacker::maybe_grow` when recursing into objects/arrays)

**Comment by RReverser** [comment]
I've tried that in a local branch, and it mostly works even with ridiculously large JSON nesting used for a test, but then stack overflow occurs deep within `drop_in_place` call chain when parsed `Value` gets deallocated.

I could add a similar guard for these deallocations, but given that user might and, most often, will parse to own data structures, I'm not sure if it should be a responsibility of serde-json to handle stack overflows in `Drop`?

**Comment by Yoric** [comment]
If necessary, how hard would it be to reimplement `drop` to avoid recursion?

**Comment by RReverser** [comment]
It wouldn't be too hard, and it should be trivial-ish to provide a newtype wrapper that would take care of this, but users would need to use it themselves in own data structures. Hence my concern about whether this belongs to serde-json or not.

**Comment by remexre** [comment]
In theory the drop method could delegate to a `depth_limited_drop` which replaces children with `Null` down to a certain recursion limit, pushing further elements into a queue; I can sketch something up in a bit.

**Comment by RReverser** [comment]
As I said, it's not really a problem to implement this for `Value` at all, but fixing it is not going to help with custom datastructures, so I'm more inclined to leave this up to the user.

**Comment by RReverser** [comment]
Also, while this fails for nesting of 64K depth, it helps with e.g. 8K depth where previously it would fail, so I guess this is still worth it.

**Comment by RReverser** [comment]
Btw, looks like there's already a separate issue for deep `Value` dropping: https://github.com/serde-rs/json/issues/440

**Comment by Yoric** [comment]
> As I said, it's not really a problem to implement this for `Value` at all, but fixing it is not going to help with custom datastructures, so I'm more inclined to leave this up to the user.

I'm not sure I follow. What kind of custom data structures are you talking about?

**Comment by RReverser** [comment]
Note that deeply nested data structures would also have problems not only with `Drop` but also with `Display` / `Debug` / `PartialEq` / `PartialOrd` ... and lots of other recursive methods, so that's why I'm arguing that this is best left to the user, and `serde-json` shouldn't do anything special (since, aside from parsing, there is lots of other ways to create such problematic instances).

**Comment by RReverser** [comment]
Hmm now that it's implemented I'm starting to wonder if a safer approach would be not growing stack indefinitely, but merely detect how much is left w/o a hardcoded depth value. This would allow users to configure their stack size via RUST_MIN_STACK or a thread builder as they normally would to prevent other stack overflows, and would still safely stop parsing when there is not enough stack left.

**Comment by dtolnay** [comment]
Fixed in 1.0.38: [`Deserializer::disable_recursion_limit`](https://docs.rs/serde_json/1.0/serde_json/struct.Deserializer.html#method.disable_recursion_limit)
