### ISSUE TITLE
v1.0.8 broke parsing of u64

### ISSUE THREAD

**Issue by jD91mZM2** [serde-rs/json#396]
Hello! I'm a user of the [discord](https://crates.io/crates/discord) crate.
When running the `get_messages` with serde_json v1.0.8, I get
```
invalid type: string "<id here>", expected a u64 or parseable string at line <line> column <column>
```
(where `<id here>` is my message ID and `<line>` and `<column>` are the line and column)

The `get_messages` simply makes a HTTP request and deserializes it into a `Vec<Message>` where `Message` is [here](https://docs.rs/discord/0.8.0/discord/model/struct.Message.html).

This works fine under v1.0.7.

**Comment by dtolnay** [comment]
Thanks for reporting this! It looks like the discord crate has been playing fast and loose with some of the deserializer API. This error is coming from [here](https://github.com/SpaceManiac/discord-rs/blob/7d475fa9868a2b4da504a4774d0ea771b393ea3f/src/serial.rs#L45) where one of the deserialize_with functions invokes `deserialize_u64`, meaning only a u64 is expected, and the JSON string `"<id here>"` is not a u64. The JSON deserializer used to incorrectly accept other types after being told to look for a u64. In this case it would be more appropriate for that function to call `d.deserialize_any(IdVisitor)` to let the input data decide what type is going to be deserialized, whether it is a string id or u64.

I also noticed an unrelated bug in [the previous function](https://github.com/SpaceManiac/discord-rs/blob/7d475fa9868a2b4da504a4774d0ea771b393ea3f/src/serial.rs#L18) -- ignoring errors like that is not a good approach in general. It can go wrong if the error is due to a syntax error in the input, not a type error. [Playground with a demo](https://play.rust-lang.org/?gist=66a84139771ca57c354a493b31456f54) showing that this can cause obviously broken JSON (mismatched quotes, invalid escape sequence) to be deserialized successfully. It can be fixed by deserializing first to something that can guarantee the input is syntactically valid, such as `serde_json::Value`. [Playground with fix.](https://play.rust-lang.org/?gist=751de68e69ac3086f7fb1440ea67da78)

If you have time, it would be good to run through the rest of the deserialization code in the discord crate and check for similar problems in other types.

**Comment by jD91mZM2** [comment]
Awesome! Thanks for doing so much digging into it!  
I suppose this is the discord crate's fault, then? I'll go open an issue there.
