### ISSUE TITLE
Tips on implementing an EDN serializer

### ISSUE THREAD

**Issue by stuarth** [serde-rs/json#408]
Hi!
I'm working on adapting serde_json to work with the [edn](https://github.com/edn-format/edn) format. JSON and edn have a lot of common ground, but one difference that I'd love to hear any thoughts on is [tagged elements](https://github.com/edn-format/edn#tagged-elements). My first approach is to write code that looks like

```rust
struct EdnDateTime(chrono::DateTime<chrono::Utc>);

use serde::ser::{self, Serialize};
use serde_edn::tagged::{EDN_STRUCT, EDN_TAG, EDN_FIELD};

impl Serialize for EdnDateTime {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: ser::Serializer,
    {
        use serde::ser::SerializeStruct;

        let mut s = serializer.serialize_struct(EDN_STRUCT, 2)?;
        s.serialize_field(EDN_TAG, "inst".as_bytes())?;
        s.serialize_field(EDN_FIELD, &self.0)?;
        s.end()
    }
}
```

And the corresponding bits in serde_edn that serialize the `EDN_TAG` field as `#inst`. That works in a narrow sense, but I'm not sure it's a good way to approach the issue generally and I'm also not sure how to extend it to compound types, e.g. if I had

```rust
struct Person {
  name: String,
  age: usize,
}
```

and wanted it it serialize as `#person {"name" "Z", "age", 4}`.

Any thoughts on the right way to model this? Thanks so much!

**Comment by dtolnay** [comment]
I think you are on the right track! One thing I would change is think about how to "make illegal states unrepresentable." In your EDN_STRUCT approach a lot of illegal states are representable: what if the struct is called EDN_STRUCT but has fewer than 2 fields or more than 2 fields, what if the fields are not called EDN_TAG and EDN_FIELD, what if they are in the wrong order, what if the EDN_TAG is not a string. A more restrictive approach would be to serialize as a newtype:

```rust
serializer.serialize_newtype_struct("edn:inst", &self.0)
```

where the Serializer prints a tag if the newtype name starts with `"edn:"`, otherwise prints only the inner value. This approach has another minor advantage in that an edn data structure serialized to almost any other format will just ignore the tag -- most Serde formats treat serialize_newtype_struct as just serializing the inner value.

For `struct Person` I would recommend providing a small custom derive that serializes its input with a given tag.

```rust
#[derive(EdnSerialize)]
#[edn = "person"] // maybe lowercase struct name would be the default if tag is not specified
struct Person {
    name: String,
    age: usize,
}
```

expands to:

```rust
impl Serialize for Person {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where S: Serializer
    {
        #[derive(Serialize)]
        #[serde(remote = "Person")]
        struct RemotePerson {
            name: String,
            age: usize,
        }

        struct Wrapper<'a>(&'a Person);
        impl<'a> Serialize for Wrapper<'a> {
            fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
                where S: Serializer
            {
                RemotePerson::serialize(self.0, serializer)
            }
        }

        serializer.serialize_newtype_struct("edn:person", &Wrapper(self))
    }
}
```

**Comment by stuarth** [comment]
Thanks @dtolnay ! I really like that approach, and I appreciate you taking the time to point me in that direction. 

Sounds like it's time to look into Syn!

**Comment by 50574E** [comment]
Hey, so how did this end up? I found this issue because I was thinking about using my summer to take a swing at this problem (EDN for Serde) as a learning exercise, it seems no one has done it yet? Is someone working on it? Sorry for the thread-necro.

**Comment by stuarth** [comment]
That'd be a fantastic project to dig into @50574E ! I don't have a lot to share from my own experience unfortunately. Best of luck!
