### ISSUE TITLE
0-copy deserialize of escaped bytes  fails with unclear error message

### ISSUE THREAD

**Issue by jorisgio** [serde-rs/json#530]
```rust
#[macro_use]
extern crate serde_derive; // 1.0.88

#[derive(Deserialize)]
struct Test<'a> {
   test: &'a str,
}

const JSON: &'static [u8] = b"{\"test\":\"foo\\u000b\"}";

fn main() {
   serde_json::from_slice::<Test>(JSON).unwrap();
}
``` 
will fail with `invalid type: string \"foo\\u{b}\", expected a borrowed string"`. Same with serde_bytes version that will fail `invalid type: byte array, expected a borrowed byte array`

This behavior makes sense, but could be documented a bit better. In an ideal world, we would have a way to deserialize json string "unescaped", but that might be too niche use-case.

I'm mostly posting this issue so that it gets indexed in google and the next poor person hitting this error might save some times :)

**Comment by dtolnay** [comment]
Thanks, closing because it is better that users look up the message and get a more complete explanation than what we can fit in an error message. Having a message explain just enough to discourage users from finding a thorough explanation would be a less good outcome.

Deserializing a borrowed string containing escape sequences could be implemented using https://docs.rs/serde_json/1.0/serde_json/value/struct.RawValue.html.

**Comment by jplatte** [comment]
> Deserializing a borrowed string containing escape sequences could be implemented using https://docs.rs/serde_json/1.0/serde_json/value/struct.RawValue.html.

How would this be done? Just by calling `RawValue`s deserialize and checking whether the first byte is a double quote, or is there more to it?

**Comment by webmaster128** [comment]
> This behavior makes sense

I think this is something worth discussing. Do you expect that a sane API deserializing

```rust
#[derive(Deserialize)]
struct Post<'a> {
   description: &'a str,
}
```

for `{ "description": "Hello, world" }` but than fail at runtime for `{ "description": "Hello \"world\"" }`? Shouldn't deserializing into borrowed strings be forbidden, since it is just not possible in the general case for JSON strings?
