### ISSUE TITLE
Serialization works for PathBuf (which is built on OsString) but not for OsString itself

### ISSUE THREAD

**Issue by paul-tcell** [serde-rs/json#550]
serde_json appears to handle PathBuf's just fine.   The output for OsString looks like some internal rust representation rather than an actual string.   Expected it to work for OsString because PathBuf is build on OsString

```
    #[test]
    fn test_osstr_ser() {
        #[derive(Serialize, Deserialize)]
        struct Foo {
            p: PathBuf,
            f: OsString
        }

        let foo = Foo {
            p: PathBuf::from("/etc/passwd"),
            f: OsString::from("passwd")
        };

        println!("output: {}", serde_json::to_string(&foo).unwrap());
    }
```
expected:
```
output: {"p":"/etc/passwd","f": "passwd"}
```
actual results:
```
output: {"p":"/etc/passwd","f":{"Unix":[112,97,115,115,119,100]}}
```

**Comment by ssokolow** [comment]
An OsString must represent bytes that a JSON String cannot represent.

PathBuf is actually broken in its current implementation in that it just pretends that all valid `OsString`s are also valid `String`s and, if you feed it POSIX paths which contain non-UTF8 bytes, serialization will fail. (See #465 for details.)

You're seeing the OsString encoded as an array of raw bytes because JSON has no bytestring type.

My workaround (which I provided code for linked from #465) is to use `\0` as an escape character and store a byte that's invalid in UTF-8 strings, such as a lone `\xe7`, as `\0\u{00e7}`. Since `\0` is the only character not allowed in paths but valid in JSON, paths which Serde currently successfully serializes will pass through unaltered. (And it's also valid as a way to encode `OsString` as long as you accept that, for non-paths which were valid before, the in-JSON representation of `\0` will change from `\0` to `\0\0`.)

**Comment by dtolnay** [comment]
https://github.com/dtolnay/request-for-implementation/issues/48 recommends how to control the bytestring JSON encoding. There are some incomplete implementations; someone would need to finish one up and publish to crates.io. But it gives the ability to serialize them in base64, or hex, or potentially utf8-with-escape-sequences.
