### ISSUE TITLE
Consider adding async methods

### ISSUE THREAD

**Issue by VictorKoenders** [serde-rs/json#575]
With the upcoming stabilization of async/await, it would be nice to add a method that would allow developers to leverage the async ecosystem.

The goal seems to be to make `futures` (now `futures-preview`) the go-to library that everyone builds upon*. 
- The trait to read from a stream is [futures::io::AsyncRead](https://docs.rs/futures-preview/0.3.0-alpha.17/futures/io/trait.AsyncRead.html).
- The trait to write to a stream is [futures::io::AsyncWrite](https://docs.rs/futures-preview/0.3.0-alpha.17/futures/io/trait.AsyncWrite.html).

Seeing as:
- async/await is not to be stabilized before 1.39,
- and not everyone might want to use this feature,
- and the minimum required version of serde would have to be raised
I think it would be wise to put this behind a feature flag, e.g. `async` or `async-std`

This would add methods to (names are bikesheddable):
- `serde_json::`: `from_async_reader`, `to_async_writer` and `to_async_writer_pretty`
- `serde_json::Serializer::`: `new_async`, `pretty_async`, `with_async_formatter`
- `serde_json::Deserializer::`: `new_async`, `from_async_reader`

*) Judging from [async_std::fs::File](https://docs.rs/async-std/0.99.9/async_std/fs/struct.File.html) which implements [async_std::io::read](https://docs.rs/async-std/0.99.9/async_std/io/trait.Read.html) which is a re-export of `futures::io::AsyncRead`

**Comment by 0xpr03** [comment]
The question is what exactly you want serde to do here. You can already use futures together with serde.
The thing you're probably looking for is streaming json support. I'm not sure how well this works at all with serde ser-/deserialization. So you probably always have to first collect the whole buffer of data and then de-/serialize it. The only thing serde could do streaming is verification of the JSON format.

**Comment by pickfire** [comment]
@VictorKoenders This is not just about adding to `serde_json`, I believe all the other `serde_*` requires this as well. I am wondering if `from_reader` could read from `AsyncRead`.

**Comment by belak** [comment]
So, the main problem with this is that the entire definition of a serializer/deserializer would need to be made async because for this to work because the deserializers read from the input assuming it's a buffer. In order for this to work, all serde traits would need to be async (or have async variants) which wouldn't be a trivial undertaking so they could call async functions inside them.

**Comment by dtolnay** [comment]
I think I would prefer not to build this into serde_json, but I would be interested to see someone else develop an async-first JSON library.

**Comment by hjfreyer** [comment]
An alternative to choosing between a "async" or "sync" model would be to remove the "inversion of control" from the library. That is, currently you construct a `Deserializer` by giving it a `Read`, and then the `Deserializer` is responsible for calling the `Read`, meaning it is sensitive to any changes to the `Read` API. It's understandable to have said, "well the `Read` API is never gonna change", but then again, here we are :P.

The alternative would be to have the `Deserializer` trait have a `next_char(u8)` method. The caller feeds in one character at a time, and the `Deserializer` manages a state machine internally, indicating at each character whether the string so far is a complete value, or incomplete, or invalid. This would be a totally self-contained and functional API, so the caller is totally in control of the flow. It's simple to build both the current API and an async API on top of such an implementation, and perhaps other APIs that callers could dream up in the future.

[Note: rather than accepting one character at a time, you'd probably want to have a `next_chars(&[u8]) -> usize` method that allows short writes like `std::io::Write`, for efficiency's sake.]

Alas, it looks like that would probably require changes to serde itself. Perhaps as async_std becomes more pervasive, serde will have to do a major revision, and maybe a change to a functional interface like this would be warranted.

**Comment by hjfreyer** [comment]
Hah, it seems there's already a proposal for that in the serde repo: https://github.com/serde-rs/serde/issues/768. I'll cross-post there.

**Comment by jmesmon** [comment]
As it may be relevant to others looking at this issue, I thought I'd share some example code.

One can write a `Decoder` which allows reading a stream of json values asynchronously. IOW, this is an async take on [`serde_json::StreamDeserializer`](https://docs.serde.rs/serde_json/struct.StreamDeserializer.html) without needing any changes made in other libraries.

```
use bytes::{Buf, BufMut};
use serde::{de::DeserializeOwned, Serialize};
use std::io::Write;
use std::marker::PhantomData;
use thiserror::Error;
use tokio_util::codec::{Decoder, Encoder};

#[derive(Debug, Error)]
pub enum Error {
    #[error("failed to read/write data: {source}")]
    Io {
        #[from]
        source: std::io::Error,
    },
    #[error("failed to decode/encode json: {source}")]
    Json { source: serde_json::Error },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct Codec<T> {
    _type: PhantomData<T>,
}

impl<T> Codec<T> {
    pub fn new() -> Self {
        Self { _type: PhantomData }
    }
}

impl<T: DeserializeOwned> Decoder for Codec<T> {
    type Item = T;
    type Error = Error;

    fn decode(&mut self, src: &mut bytes::BytesMut) -> Result<Option<Self::Item>, Self::Error> {
        let (v, consumed) = {
            let mut i = serde_json::Deserializer::from_slice(src).into_iter();
            let v = match i.next().unwrap_or(Ok(None)) {
                Ok(v) => Ok(v),
                Err(e) => {
                    if e.classify() == serde_json::error::Category::Eof {
                        Ok(None)
                    } else {
                        Err(Error::Json { source: e })
                    }
                }
            };
            (v, i.byte_offset())
        };
        src.advance(consumed);
        v
    }
}

impl<T, S: Serialize> Encoder<S> for Codec<T> {
    type Error = Error;

    fn encode(&mut self, item: S, dst: &mut bytes::BytesMut) -> Result<(), Self::Error> {
        let mut w = dst.writer();
        serde_json::to_writer(&mut w, &item).map_err(|source| Error::Json { source })?;
        // NOTE: you may or may not need/want this
        w.write_all(b"\n")?;
        Ok(())
    }
}
```

note the downside here that a hostile AsyncRead could cause an exponential parse time (by emiting 1 byte at a time, causing this Decoder to re-parse the data repeatedly). This could likely be avoided if serde_json could keep intermediate parse state on EOF and Decoder was either avoided or adjusted to allow tracking other data (in this case, the intermediate parse state).
