### ISSUE TITLE
Feature request (or question):  how to use both preserve_order and no preserve_order in a same rust program

### ISSUE THREAD

**Issue by c0b** [serde-rs/json#576]
new rust user here, so far as I understand, this crate has a `preserve_order` feature it's using standard Cargo's feature, at compile time you need to decide to build with a feature or without;
https://doc.rust-lang.org/cargo/reference/manifest.html#the-features-section

but, is there anyway can build a rust program with both sides? with and without?
https://crates.io/crates/features          (something like this feature toggles at runtime?)

Specifically,  I'm looking into some equivalent code to Python's ::

```python
    # this default loads will use Python default dict, an unpredictable order
    obj = json.loads(data)

    # this loads JSON object into an OrderedDict
    obj = json.loads(data, object_pairs_hook=collections.OrderedDict)
```

**Comment by jplatte** [comment]
This is not possible, but it's not *that* hard to define your own equivalent to `serde_json::Value` that always reorders the elements even if `preserve_order` is enabled in `serde_json`. We did this in Ruma, because we needed a slightly stripped-down version of `serde_json::Value` that disallows floats (and integers above JavaScript's `MAX_SAFE_INTEGER`): https://github.com/ruma/ruma/blob/0beeb6ef9b0e29c76f5f0235c28329c2061f2a51/crates/ruma-serde/src/canonical_json/value.rs

**Comment by dtolnay** [comment]
Yep `serde_json::Value` will behave just one way, but you can have your own enum + Deserialize impl which follows the ordering that you want.
