### ISSUE TITLE
How to detect if a string is a valid json ?

### ISSUE THREAD

**Issue by clintnetwork** [serde-rs/json#579]
Thank you :)

**Comment by ssokolow** [comment]
This isn't a support tracker but, since seeing this sitting empty is bugging me and I don't have permission to close it, I'll try to answer.

Given the nature of JSON, you validate it by attempting to parse it. If you parse it into a struct, the struct will function as a schema you're validating it against.

If you just want to check that it's well-formed, parse it into `Value` and see if you get an error.

Here's the relevant line from the README:

```rust
let v: Value = serde_json::from_str(data)?;
```

**Comment by clintnetwork** [comment]
Yes, I'm really sorry, I mustn't use GitHub like a support center, but thank you for the answer!

**Comment by santhosh-tekuri** [comment]
using `IgnoredAny` should be a more efficient way to do this check:

```rust
let _: serde::de::IgnoredAny = serde_json::from_str(data)?;
```
