### ISSUE TITLE
Curious serialization of Option<()>

### ISSUE THREAD

**Issue by mbernat** [serde-rs/json#631]
Consider the following code.
```rust
use serde::Serialize;

#[derive(Serialize)]
enum Bar {
    X { a: Option<()>, b: Option<()> },
}

fn main() {
    let bar = Bar::X{a: None, b: Some(())};
    let serialized = serde_json::to_string(&bar).unwrap();
    println!("serialized = {}", serialized);
}
```

The output might surprise you.
```
serialized = {"X":{"a":null,"b":null}}
```
This sure looks like a bug to me: both values map to `null` but they shouldn't, `Option<()>` is equivalent to `bool`!

This also happens when you nest several options types.

I also wonder if other similar structures could be affected by this kind of flattening.

**Comment by dtolnay** [comment]
This is intended. JSON doesn't have a native concept of Option so we serialize Some as the inner value. If you want None and Some always distinguishable, you would need to use a format other than JSON.

**Comment by mbernat** [comment]
Very strange choice since it is possible to encode enums in JSON and you do support enum serialization (Option is just a particular enum type).

Should I be wary when using enums with JSON too? Destroying information like this for no good reason is unexpected, to say the least.

**Comment by dtolnay** [comment]
Yes -- if this design is unexpected then you should be wary of using JSON at all.

**Comment by mbernat** [comment]
Thanks for the heads up!

**Comment by 42triangles** [comment]
Sorry for commenting on this rather old issue, but I have come across the same underlying issue while working on weird macro stuff that might end up trying to serialise nested `Option`s which exhibit the same issue (`None` & `Some(None)` both serialise to `null`).
Based on the source code of `serde_json` (https://docs.rs/serde_json/1.0.87/src/serde_json/ser.rs.html#270-280) I *think* those two are the only instances of this specific issue though (there might be other types not surviving roundtrips too, but they would fail because of different things).

> if this design is unexpected then you should be wary of using JSON at all.

If that is the philosophy of this crate, I think the README and/or documentation (the latter probably suffices though) should probably be changed to reflect that. Currently the README contains these passages:
> * **As a strongly typed Rust data structure.** When you expect all or most of your data to conform to a particular structure and want to get real work done without JSON's loosey-goosey nature tripping you up.

and
> Serde JSON provides efficient, flexible, safe ways of converting data between each of these representations.

And the documentation only says this:
> Serialization can fail if `T`’s implementation of `Serialize` decides to fail, or if `T` contains a map with non-string keys.

I feel like they suggest that this shouldn't be an issue.

That said, `Option<()>` and `Option<Option<T>>` are probably rare enough that it doesn't really come up (in fact I just found out about it because I was curious how `serde_json` handles `Option<Option<T>>` by default because I was doing some weird macro things that might end up with nested options, and there appears to be no GitHub issue on this repository about nested options), so while the error can be caught (by storing in the serializer if the current type is in the context of a `Some` already, in which case it could default to something similar to "normal" enums instead), the performance implications (though I haven't measured anything, and in fact due to being generic those checks might be completely optimised away) & potential breakage of existing usages might possibly not be worth it - though I personally don't feel comfortable making such a judgement.
