### ISSUE TITLE
 Serializing std::fs::Metadata

### ISSUE THREAD

**Issue by darakian** [serde-rs/json#683]
Hey all, 

I'm trying to add the `std::fs::Metadata` struct as a member of a struct for which I am deriving serialization and serde doesn't seem to like it. I'm seeing errors like
```
  --> src/lib.rs:43:5
   |
43 |     meta: Metadata,
   |     ^^^^ the trait `_IMPL_SERIALIZE_FOR_Fileinfo::_serde::Serialize` is not implemented for `std::fs::Metadata`
   |
   = note: required by `_IMPL_SERIALIZE_FOR_Fileinfo::_serde::ser::SerializeStruct::serialize_field`
```

I've made a small struct to test this 
```
#[derive(Debug, Serialize)]
pub struct test{
    meta: Metadata,
}
```

Is the metadata struct simply not serializable at the moment? If so, why not? If not, am I missing something?

**Comment by dtolnay** [comment]
Correct, there isn't a serde Serialize impl for std::fs::Metadata.

If you need to serialize one (keeping in mind that deserializing won't work, because there is no way to construct a std::fs::Metadata with specific values in it) then it would be reasonable to ask for that behavior from a helper crate, such as https://github.com/jonasbb/serde_with.

**Comment by darakian** [comment]
> there is no way to construct a std::fs::Metadata with specific values in it

Why is that exactly?
