### ISSUE TITLE
Support Unicode Plane >= 1 represented as UTF16BE 

### ISSUE THREAD

**Issue by zonyitoo** [serde-rs/json#731]
```json
{
    "JP_flag": "\uD83C\uDDEF\uD83C\uDDF5"
}
```

This is a valid JSON, although `\uD83C` is not in valid Unicode range. It is a Japanese Nation Flag (🇯🇵), which consists of 2 Unicode Code Point `U+1F1EF, U+1F1F5`.

Since JSON's standard can only represent Unicode Plane 0 (`\u0000` - `\uFFFF`), some libraries will output it as UTF16BE, like Python.

```python
import json
v = u'\U0001F1EF\U0001F1F5'
x = json.dumps(v)
print(x)
# "\ud83c\uddef\ud83c\uddf5"
```

I think serde_json's parser should be able to parse these UTF16BE strings.

**Comment by SirWindfield** [comment]
Maybe this is related to my problem that I stumbled across. I have a JSON file containing `"⬆️ "`. I deserialise the file and use `quote` to construct structs from it holding the data. The problem is that some emojis contain the `Unicode Variant Selector`. The above emoji gets written back into the file as `⬆\u{fe0f}`. For some reason, something is inserting the variant selector.

I don't think it's `quote` as the only dependency it has is `proc-macro2`. I don't think it's my code actually:

```rust
let file_content = fs::read_to_string("./data_with_emoji.json")?;
let struct_: Struct = serde_json::from_str(&file_content)?;
let slice_of_str_with_emoji = struct_.slice;
let name = "generated";

quote! {
    pub const #name: crate::Data<'static> = crate::Data {
        data: &[
            #(#slice_of_str_with_emoji),*
        ],
    };
}
```

I hate pinging people, but since you have a lot of inside knowledge on these crates, you might know what's wrong here @dtolnay.
