### ISSUE TITLE
Unexpected mismatch between serialize/deserialize w/ macro driven casing

### ISSUE THREAD

**Issue by nkconnor** [serde-rs/json#783]
I couldn't find an issue for this and it seems like a pretty common usage so just guessing I'm overlooking something - with internal enum tagging and rename_all="camelCase" the deserializer works as expected but the serializer tags everything in KebabCase. 

Here's a minimal example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0ca54c70b0ee37c70cd5021a273fdb48

**Comment by jonasbb** [comment]
This seems to be more related to the derive than to the JSON implementation. When you serialize to a string you see better what is going on.
```json
{"type":"paperWasp","type":"PaperWasp","age":5,"hiveLocation":"Somewhere"}
```

Both the `Bug` enum and the `PaperWasp` struct serialize a field `type`. JSON does not prohibit duplicate keys. However, the meaning of duplicate keys is not well-defined. The `Value` type seems to choose the last occurring one, which is why you don't see it when printing.
The `rename_all` on the struct will only rename the fields but not the struct itself, but since duplicate keys are not ideal, you might want to remove the `tag` annotation on `PaperWasp`.

**Comment by nkconnor** [comment]
Thanks! I knew there was something I must be missing
