### ISSUE TITLE
How to skip & rename field in custom serialization/deserialization of particular field?

### ISSUE THREAD

**Issue by tejHackerDEV** [serde-rs/json#946]
Hi, I am looking for a way to skip the way if it is optional while serializing. I know there is a way with serde annotations to use like Option::is_none & rename. But the problem is I want to annotate it for across different models (so in future if it gets changed need to update across different models). I tried looking up with #513 but in that it is an complete struct in my case I want to use it with a single field of struct not on all. I tried setting serialize_unit() but is it treating it as null value but passing unit should skip it, because we have serialize_none() any way which will return null value if needed.

Example:-
```Rust
pub struct User {
    #[serde(with = "hex_string")]
    id: Option<String>,
    email: String,
    password: String,
}

pub mod hex_string {
    use serde::{Deserialize, Deserializer, Serialize, Serializer};

    pub fn serialize<S>(value: &Option<String>, s: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        // Want to skip the field if none & should have an option to rename the key
    }

    pub fn deserialize<'de, D>(d: D) -> Result<Option<String>, D::Error>
    where
        D: Deserializer<'de>,
    {
        // Can rename the key & deserialize it
    }
}

```

**Comment by jonasbb** [comment]
The serde attributes `skip_serializing_if` and `rename` are your only option here, except from manually writing the `Serialize` and `Deserialize` implementations.
The module you specify using `with` is only responsible for serializing a value. It does not control the name or if it gets invoked in the first place. The name is directly controlled by the `User` struct implementations. These implementations also govern if a field is skipped or not, since this is important for the serialization of `User` itself, e.g., to determine the length.

**Comment by tejHackerDEV** [comment]
Thanks for the clarification @jonasbb. I am closing this as it is irrelevant to ask for the feature request too
